$('#member_menu').click(function(){
	$('#home_menu').attr('class','');
	$('#member_menu').attr('class','active');
	$('#item_menu').attr('class','');
	$('#qna_menu').attr('class','');
	$('#setting_menu').attr('class','');
});
$('#home_menu').click(function(){
	$('#home_menu').attr('class','active');
	$('#member_menu').attr('class','');
	$('#item_menu').attr('class','');
	$('#qna_menu').attr('class','');
	$('#setting_menu').attr('class','');
})
$('#item_menu').click(function(){
	$('#home_menu').attr('class','');
	$('#member_menu').attr('class','');
	$('#item_menu').attr('class','active');
	$('#qna_menu').attr('class','');
	$('#setting_menu').attr('class','');
})
$('#qna_menu').click(function(){
	$('#home_menu').attr('class','');
	$('#member_menu').attr('class','');
	$('#item_menu').attr('class','');
	$('#qna_menu').attr('class','active');
	$('#setting_menu').attr('class','');
})
$('#setting_menu').click(function(){
	$('#home_menu').attr('class','');
	$('#member_menu').attr('class','');
	$('#item_menu').attr('class','');
	$('#qna_menu').attr('class','');
	$('#setting_menu').attr('class','active');
})